---
# provisioning des serveurs de données
- hosts: database
  pre_tasks:
    - name: Read vars from file
      include_vars: vars.yml

  roles:
    - commun
    - database

# provisioning des serveurs web
- hosts: web
  pre_tasks:
    - name: Read vars from file
      include_vars: vars.yml

  roles:
    - commun
    - web
