---
# tasks file for common

- name: Installation des logiciels communs
  apt: 
    pkg: ["vim", "tree", "htop"]  
    state: latest 
    update_cache: yes
  become: yes
- name: tooling docker
  apt: 
    pkg: ["docker.io", "python3-docker"]
    state: latest 
  become: yes
- name: tooling mysql
  apt: 
    pkg: ["mysql-client", "python3-mysqldb"]
    state: latest 
  become: yes
